#!/bin/bash
for DB in `su postgres -c "psql -At -c \"select datname from pg_database where datistemplate = false and 'postgres' <> datname;\" postgres"`
do
        echo $DB
        su odoo -c "odoobackup --database=$DB --filename=/tmp/odoobackup.$$" && mv /tmp/odoobackup.$$ /var/backups/"$DB".zip
	if [ -f /tmp/odoobackup.$$ ] 
	then
		rm -f /tmp/odoobackup.$$ ; echo Database $DB not backedup
		su postgres -c "pg_dump -Fp $DB " | gzip > /var/backups/"$DB".sql.gz
	fi
done

#
#  odoobackup uses large amount space on /tmp, if this a problem bind a large partion to /tmp
#  sudo mount -o bind /var/tmp /tmp  # bind tmp-directory from /var to /tmp
# /etc/fstab:
#  /var/tmp /tmp 	none	defaults,bind	0	0
#
