#!/usr/bin/bash
################################################################################
#                                                                              #
#       Installation of several Odoo-Repositories that are commonly used       #
#                                                                              #
################################################################################

TARGETDIR="/usr/share"
REPOPREFIX='odoo'

echo "Installing additional repos"
sudo odooextras.py repos

echo "Installing requirements with apt"

echo "Installing requirements with pip3"

for repo in $(ls $TARGETDIR | grep ^$REPOPREFIX) ; do
    REQUIREMENTS=$TARGETDIR/$repo/requirements.txt
    if test -f $REQUIREMENTS ; then
	echo "Installing requirements from: "$REQUIREMENTS
        sudo pip3 install -r $REQUIREMENTS
    fi
done

echo "changing name on excludes l10n_se module so that it doesn't conflict with our own l10n_se module"
FILE=/usr/share/core-odoo/addons/l10n_se
if [ -f "$FILE" ]; then
    echo "$FILE exists. Changing name of $FILE"
    sudo mv /usr/share/core-odoo/addons/l10n_se /usr/share/core-odoo/addons/exclude_l10n_se   
fi

FILE2=/usr/share/core-odoo/addons/l10n_se_ocr
if [ -f "$FILE2" ]; then
    echo "$FILE2 exists. Changing name of $FILE2"
    sudo mv /usr/share/core-odoo/addons/l10n_se_ocr /usr/share/core-odoo/addons/exclude_l10n_se_ocr  
fi


echo "Install done!"

