#!/bin/bash
################################################################################
#                                                                              #
#   Installation of Odootools - Tools to help manage an Odoo installation      #
#                                                                              #
#                                                                              #
#                                                                              #
################################################################################

echo "Performing basic prerequisite checks ..."

echo "Download common files..."
wget -O- https://raw.githubusercontent.com/vertelab/odootools/common/install | bash

