#!/bin/bash
################################################################################
#                                                                              #
#   Installation of Odootools - Tools to help manage an Odoo installation      #
#                                                                              #
#                                                                              #
#                                                                              #
################################################################################

echo "Performing basic prerequisite checks ..."

VERSION=14.0
echo "Download common files..."
wget -O- https://raw.githubusercontent.com/vertelab/odootools/common/install | bash > /tmp/tmpinstallcommon.sh
bash /tmp/tmpinstallcommon.sh $VERSION
