#!/bin/bash



if [ ! -d /etc/odoo ]; then  # Install Odoo (only one time)
    # this package is missing in 16.04 
    wget https://launchpad.net/ubuntu/+archive/primary/+files/python-support_1.0.15_all.deb
    sudo dpkg -i python-support_1.0.15_all.deb
    sudo apt -y install python-xlwt python-xlsxwriter python-werkzeug python-vobject python-vatnumber python-tz python-suds python-requests python-reportlab python-pyparsing python-pydot python-pychart python-psycopg2 python-psutil python-passlib python-openid python-mako python-libxslt1 python-ldap python-jinja2 python-feedparser python-docutils python-decorator python-dateutil python-babel postgresql-client node-less

    wget http://ftp.se.debian.org/debian/pool/main/p/python-pypdf/python-pypdf_1.13-2_all.deb
    sudo dpkg -i python-pypdf_1.13-2_all.deb
    
    wget http://ftp.se.debian.org/debian/pool/main/p/pillow/python-imaging_4.0.0-4_all.deb
    sudo dpkg -i python-imaging_4.0.0-4_all.deb
    
    sudo apt -y install postgresql

    sudo wget -O - https://nightly.odoo.com/odoo.key | sudo apt-key add -
    echo "deb http://nightly.odoo.com/10.0/nightly/deb/ ./" | sudo tee /etc/apt/sources.list.d/odoo.list > /dev/null
    sudo apt-get update
    sudo apt-get -y install odoo
    # Generate a good password
    sudo perl -i -pe 'BEGIN { $pw.=(a..z,A..Z,0..9)[rand 62] for 0..15 } s/; admin_passwd.*$/admin_passwd = $pw/g' /etc/odoo/odoo.conf
    sudo wget -O /etc/odoo/odoo.tools https://raw.githubusercontent.com/vertelab/odootools/10.0/odoo.tools
    sudo -u postgres bash -c "createuser odoo"
fi


if [ ! -d /usr/share/core-odoo ]; then 
    sudo ln -s /usr/lib/python2.7/dist-packages/odoo/ /usr/share/core-odoo
fi

sudo apt-get -y install python-dev libffi-dev
sudo pip install pybarcode
sudo apt-get install -y python-cairosvg
sudo pip install utils
sudo apt-get -y install python-pip
sudo apt -y install python-openpyxl
sudo apt-get -y install git
sudo pip install phonenumbers
sudo pip install erppeek
sudo pip install xlrd
sudo pip install openpyxl
sudo pip install unicodecsv

sudo wget -O /etc/profile.d/odootools.sh https://raw.githubusercontent.com/vertelab/odootools/10.0/odootools.sh
sudo wget -O /etc/bash_completion.d/odoo https://raw.githubusercontent.com/vertelab/odootools/10.0/bash_completion.odoo
# Systemd
sudo wget -O /etc/systemd/system/odoo.service https://raw.githubusercontent.com/vertelab/odootools/10.0/odoo.service
sudo systemctl daemon-reload
sudo systemctl enable odoo
sudo systemctl start odoo

wget -O /tmp/wkhtmltox_0.12.1.3-1~bionic_amd64.deb https://builds.wkhtmltopdf.org/0.12.1.3/wkhtmltox_0.12.1.3-1~bionic_amd64.deb
sudo dpkg -i /tmp/wkhtmltox_0.12.1.3-1~bionic_amd64.deb
sudo apt -fy install
sudo rm -f /tmp/wkhtmltox_0.12.1.3-1~bionic_amd64.deb

# daily backup
sudo wget -O /etc/cron.daily/db_backup https://raw.githubusercontent.com/vertelab/odootools/10.0/db_backup
sudo chmod a+x /etc/cron.daily/db_backup


. /etc/profile.d/odootools.sh
. /etc/bash_completion
