#!/bin/bash
# .git/hooks/post-checkout
# git checkout 17.0 will run this script

# Get the current branch name
branch_name=$(git rev-parse --abbrev-ref HEAD)

# Get the repository name
repo_name=$(basename `git rev-parse --show-toplevel`)

# sudo pip3 install preprocessor ; preprocessor --help


## Python
#
#    Python (*.p.py), Javascript (*.p.js), csv (*.p.csv)
#
#        # #if VERSION == "main"
#        ...
#        # #elif VERSION == 17.0
#        ...
#        # #else
#        ...
#        # #endif#
#
#    Replacement:
#
#    ##VERSION## ->  17.0
#    ##REPO##    ->  odoo-base
#
find . -name "*.p.py" | xargs -I {} sh -c 'base=$(echo {}); preprocess -D VERSION=${branch_name} -D REPO=${repo_name} -o "${base%.p.py}.py" "{}"'
find . -name "*.py" ! -name "*.p.py" | xargs -I {} perl -i -p -e "s/##VERSION##/${branch_name}/g" {} 
find . -name "*.py" ! -name "*.p.py" | xargs -I {} perl -i -p -e "s/##REPO##/${repo_name}/g" {} 
## JS
find . -name "*.p.js" | xargs -I {} sh -c 'base=$(echo {}); preprocess -D VERSION=${branch_name} -D REPO=${repo_name} -o "${base%.p.js}.js" "{}"'
find . -name "*.js" ! -name "*.p.js" | xargs -I {} perl -i -p -e "s/##VERSION##/${branch_name}/g" {} 
find . -name "*.js" ! -name "*.p.js" | xargs -I {} perl -i -p -e "s/##REPO##/${repo_name}/g" {} 
## CSV
find . -name "*.p.csv" | xargs -I {} sh -c 'base=$(echo {}); preprocess -D VERSION=${branch_name} -D REPO=${repo_name} -o "${base%.p.csv}.csv" "{}"'
find . -name "*.csv" ! -name "*.p.csv" | xargs -I {} perl -i -p -e "s/##VERSION##/${branch_name}/g" {} 
find . -name "*.csv" ! -name "*.p.csv" | xargs -I {} perl -i -p -e "s/##REPO##/${repo_name}/g" {} 
## XML
#
#        <!-- #if VERSION == 17.0 -->
#        ...
#        <!-- #endif -->
#
find . -name "*.p.xml" | xargs -I {} sh -c 'base=$(echo {}); preprocess -D VERSION=${branch_name} -D REPO=${repo_name} -o "${base%.p.xml}.xml" "{}"'
find . -name "*.xml" ! -name "*.p.xml" | xargs -I {} perl -i -p -e "s/##VERSION##/${branch_name}/g" {} 
find . -name "*.xml" ! -name "*.p.xml" | xargs -I {} perl -i -p -e "s/##REPO##/${repo_name}/g" {} 
